typography_spectrum: 0.4701594489160925
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9920110050588846
  lightness: 0.968569906661287
  saturation: 0.5340123625937849
  rhythmicContrast: 0.4999582569580525
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4319626309443265
analytics:
  google: null
  facebook: null
  twitter: null
name: Blue Bird Travels
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
